#! /bin/sh

PROFILE=${1}
REPO=${2}
REPO_URL=`git-multi-profile --format-url --profile=${PROFILE} --repo=${REPO}`
if [ "$?" -ne "0" ]; then
  exit 1
fi

echo ${REPO_URL}
git clone ${REPO_URL}
if [ "$?" -ne "0" ]; then
  exit 1
fi

REPO_NAME=`git-multi-profile --get-repo-name --profile=${PROFILE} --repo=${REPO}`
if [ "$?" -ne "0" ]; then
  exit 1
fi
cd ${REPO_NAME}
git-multi-profile --set-local-profile --profile=${PROFILE}
